on: [push]

jobs:
  icarus_simulation_job:
    runs-on: ubuntu-latest
    name: A job to run simulations via icarus verilog
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Simulate 
        id: sim
        uses: ./
      - name: Artifacts
        id: artifacts
        uses: actions/upload-artifact@v3
        with:
          name: waveforms
          path: |
            !./program/common/
            ./program/*/sim/dump.vcd