on: [push]

jobs:
  icarus_simulation_job:
    runs-on: ubuntu-latest
    name: A job to run simulations via icarus verilog
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3
      - name: Run simulation action step 
        id: sim
        uses: ./